### ISSUE TITLE
can't be used with in the modal

### ISSUE THREAD

**Issue by NitinSidhu** [YanYuanFE/react-native-signature-canvas#59]
i tried to use the Signature-Canvas with in the **modal**, but is shows nothing. can you help.

**Comment by YanYuanFE** [comment]
provide your code example and version.

**Comment by BlerasKRT** [comment]
it works for me

**Comment by luminousAvocado** [comment]
Hi i'm trying to use this within a modal but every time i open the modal, it changes screens so that it only shows the signature.

![image](https://user-images.githubusercontent.com/28456419/94730190-b1613100-0317-11eb-8037-760ad75fc816.png)

This is the code on my screen, which on click, makes the modal visible. Without the Signature, the modal will show, with the Signature, it changes screens

![image](https://user-images.githubusercontent.com/28456419/94730304-dfdf0c00-0317-11eb-86f7-519dd4dd7a76.png)

How did you get it to work @BlerasKRT ? I have version 3.1.0
